version: '3.7'

services:
    db :
        image: mysql:latest
        restart: always
        volumes: 
            - db_data:/var/lib/mysql/
        environment: 
            MYSQL_ROOT_PASSWORD: password
        expose: 
            - 3306
    scripts :
        build:
            context: .
        image: file_server
        ports: 
            - 9001:9001
        volumes: 
            - data:/root/
volumes:
    db_data:
    data:
